✨ Feat: Add `all_users_total_xp` function and route
source-academy/backend pull request #914
Opened 2022-10-13 09:28 UTC by ShenyiCui

2023-01-08 14:11 UTC, chownces requested changes

2023-01-08 14:11 UTC, chownces commented on test/cadet_web/admin_controllers/admin_user_controller_test.exs
> +  describe "GET /v2/courses/{course_id}/user/total_xp" do
these are copied over from `user_controller_test.exs`? could we have some tests for the correct admin endpoint?

2023-01-08 14:11 UTC, chownces commented on lib/cadet_web/admin_controllers/admin_user_controller.ex
> +    combined_user_xp_total_query = """
could you place this query under the `Achievements` context instead of the controller layer? i.e. `lib/cadet/incentives/achievements.ex`

2023-06-16 13:00 UTC, RichDom2185 requested changes

2023-07-15 17:28 UTC, RichDom2185 commented
Related frontend PR (merged): https://github.com/source-academy/frontend/pull/2281

2024-02-13 08:31 UTC, RichDom2185 commented
As discussed offline, we will close this PR and revert the already-merged frontend change.

2024-02-13 08:31 UTC, closed without merging