Add Endpoints for Notifications
source-academy/backend pull request #950
Opened 2023-06-14 08:08 UTC by Santosh3007

## Changes

Adding extra endpoints needed for notifications

2023-06-20 16:56 UTC, YaleChen299 requested changes
Thanks for the quick work! However, I think the design needs major changes. 

First of all, try to follow the current routing scopes, if a notification belongs to a course, semantically it should be under /course. In that way, you will naturally pipe through authentication checks, course checks sand staff checks. 

Second, please separate admin routes from student routes (or do you want to separate them from staff also?). Do think about the privilege of each route. The backend needs to be intact without the assumption of the well-behaviour of the frontend.

Lastly, please clean up unnecessary comments and use query styles in the piping fashion(which aligns with the current code base). Try to use Logger instead of IO for logging.

2023-06-20 16:56 UTC, YaleChen299 commented on lib/cadet_web/router.ex
> +  # Notifications endpoints
How are these APIs being called from the frontend? Why are they not piped through authentication and course-specific assignment? I am not sure what might happen here. If some request is fired from a student that already has his log in session expired or if the student changed course(which might lead to some cache issue or privilege issue)...

2023-06-20 16:56 UTC, YaleChen299 commented on lib/cadet_web/router.ex
> +  # Notifications endpoints
Also please separate the admin routes from the student routes

2023-06-20 16:56 UTC, YaleChen299 commented on lib/cadet_web/controllers/new_notifications_controller.ex
> +    # JUNYI AND SANTOSH: NOT DEFINED???
please clean up unused comments as well.

2023-07-25 03:43 UTC, YaleChen299 commented
This PR is superseded by #973. Hence, this will be closed when #973 is merged.

2024-08-12 01:00 UTC, RichDom2185 commented
Closing as per offline discussion.

2024-08-12 01:00 UTC, closed without merging